# Generated by Django 3.2.3 on 2021-07-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField(unique=True)),
                ('photo', models.ImageField(upload_to='student_images')),
                ('email', models.EmailField(max_length=30)),
                ('date_of_regi', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
