# Generated by Django 3.2.3 on 2021-07-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app17', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistationmodel',
            name='dob',
            field=models.DateField(default='2021-06-01'),
        ),
    ]
